# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 70, 20, 391))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(370, 340, 361, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.horizontalScrollBar_2.setFont(font)
        self.horizontalScrollBar_2.setStyleSheet("background-color:rgb(0, 0, 255);")
        self.horizontalScrollBar_2.setMaximum(255)
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.horizontalScrollBar_3 = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_3.setGeometry(QtCore.QRect(370, 200, 361, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.horizontalScrollBar_3.setFont(font)
        self.horizontalScrollBar_3.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.horizontalScrollBar_3.setMaximum(255)
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        self.horizontalScrollBar_4 = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_4.setGeometry(QtCore.QRect(370, 270, 361, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.horizontalScrollBar_4.setFont(font)
        self.horizontalScrollBar_4.setStyleSheet("background-color:rgb(0, 255, 0)")
        self.horizontalScrollBar_4.setMaximum(255)
        self.horizontalScrollBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_4.setObjectName("horizontalScrollBar_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 71))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color : rgb(255, 229, 44);")
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 801, 2))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 110, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:transparent")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 180, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:transparent")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 250, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:transparent")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, 320, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent")
        self.label_5.setObjectName("label_5")
        self.SEND = QtWidgets.QPushButton(self.centralwidget)
        self.SEND.setGeometry(QtCore.QRect(390, 390, 120, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SEND.setFont(font)
        self.SEND.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:pressed{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.SEND.setObjectName("SEND")
        self.EXIT = QtWidgets.QPushButton(self.centralwidget)
        self.EXIT.setGeometry(QtCore.QRect(540, 390, 120, 31))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.EXIT.setFont(font)
        self.EXIT.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:pressed{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.EXIT.setObjectName("EXIT")
        self.B = QtWidgets.QLabel(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(300, 344, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        self.B.setFont(font)
        self.B.setStyleSheet("background-color:transparent")
        self.B.setObjectName("B")
        self.R = QtWidgets.QLabel(self.centralwidget)
        self.R.setGeometry(QtCore.QRect(300, 204, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        self.R.setFont(font)
        self.R.setStyleSheet("background-color:transparent")
        self.R.setObjectName("R")
        self.G = QtWidgets.QLabel(self.centralwidget)
        self.G.setGeometry(QtCore.QRect(300, 274, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        self.G.setFont(font)
        self.G.setStyleSheet("background-color:transparent")
        self.G.setObjectName("G")
        self.W = QtWidgets.QLabel(self.centralwidget)
        self.W.setGeometry(QtCore.QRect(300, 134, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(12)
        self.W.setFont(font)
        self.W.setStyleSheet("background-color:transparent")
        self.W.setObjectName("W")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 100, 211, 321))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.pushButton1 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton1.sizePolicy().hasHeightForWidth())
        self.pushButton1.setSizePolicy(sizePolicy)
        self.pushButton1.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton1.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton1.setCheckable(True)
        self.pushButton1.setObjectName("pushButton1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton1)
        self.lineEdit1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit1.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit1.setObjectName("lineEdit1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit1)
        self.pushButton2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton2.sizePolicy().hasHeightForWidth())
        self.pushButton2.setSizePolicy(sizePolicy)
        self.pushButton2.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton2.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton2.setFont(font)
        self.pushButton2.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton2.setCheckable(True)
        self.pushButton2.setObjectName("pushButton2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton2)
        self.lineEdit2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit2.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit2.setObjectName("lineEdit2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit2)
        self.pushButton3 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton3.sizePolicy().hasHeightForWidth())
        self.pushButton3.setSizePolicy(sizePolicy)
        self.pushButton3.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton3.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton3.setFont(font)
        self.pushButton3.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton3.setCheckable(True)
        self.pushButton3.setObjectName("pushButton3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton3)
        self.lineEdit3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit3.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit3.setObjectName("lineEdit3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit3)
        self.pushButton4 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton4.sizePolicy().hasHeightForWidth())
        self.pushButton4.setSizePolicy(sizePolicy)
        self.pushButton4.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton4.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton4.setFont(font)
        self.pushButton4.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton4.setCheckable(True)
        self.pushButton4.setObjectName("pushButton4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton4)
        self.lineEdit4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit4.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit4.setObjectName("lineEdit4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit4)
        self.pushButton5 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton5.sizePolicy().hasHeightForWidth())
        self.pushButton5.setSizePolicy(sizePolicy)
        self.pushButton5.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton5.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton5.setFont(font)
        self.pushButton5.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton5.setCheckable(True)
        self.pushButton5.setObjectName("pushButton5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton5)
        self.lineEdit5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit5.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit5.setObjectName("lineEdit5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit5)
        self.pushButton6 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton6.sizePolicy().hasHeightForWidth())
        self.pushButton6.setSizePolicy(sizePolicy)
        self.pushButton6.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton6.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton6.setFont(font)
        self.pushButton6.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton6.setCheckable(True)
        self.pushButton6.setObjectName("pushButton6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton6)
        self.lineEdit6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit6.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit6.setObjectName("lineEdit6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit6)
        self.pushButton7 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton7.sizePolicy().hasHeightForWidth())
        self.pushButton7.setSizePolicy(sizePolicy)
        self.pushButton7.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton7.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton7.setFont(font)
        self.pushButton7.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton7.setCheckable(True)
        self.pushButton7.setObjectName("pushButton7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton7)
        self.lineEdit7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit7.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit7.setFont(font)
        self.lineEdit7.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit7.setObjectName("lineEdit7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit7)
        self.pushButton8 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton8.sizePolicy().hasHeightForWidth())
        self.pushButton8.setSizePolicy(sizePolicy)
        self.pushButton8.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton8.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton8.setFont(font)
        self.pushButton8.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton8.setCheckable(True)
        self.pushButton8.setObjectName("pushButton8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pushButton8)
        self.lineEdit8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit8.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit8.setFont(font)
        self.lineEdit8.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit8.setObjectName("lineEdit8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit8)
        self.pushButton9 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton9.sizePolicy().hasHeightForWidth())
        self.pushButton9.setSizePolicy(sizePolicy)
        self.pushButton9.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton9.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton9.setFont(font)
        self.pushButton9.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton9.setCheckable(True)
        self.pushButton9.setObjectName("pushButton9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pushButton9)
        self.lineEdit9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit9.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit9.setFont(font)
        self.lineEdit9.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit9.setObjectName("lineEdit9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit9)
        self.pushButton10 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton10.sizePolicy().hasHeightForWidth())
        self.pushButton10.setSizePolicy(sizePolicy)
        self.pushButton10.setMinimumSize(QtCore.QSize(75, 22))
        self.pushButton10.setMaximumSize(QtCore.QSize(16777215, 22))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.pushButton10.setFont(font)
        self.pushButton10.setStyleSheet("QPushButton{border: 2px solid rgba(255, 180, 0);border-radius:5px;}\n"
"QPushButton:checked{border: 2px solid rgba(255, 180, 0);\n"
"background-color:qlineargradient(spread:reflect, x1:0.483889, y1:0, x2:0.500333, y2:0.512,stop:0 rgba(255, 180, 0, 255), stop:1 rgba(255, 229, 44, 255));\n"
"border-radius:5px;}")
        self.pushButton10.setCheckable(True)
        self.pushButton10.setObjectName("pushButton10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pushButton10)
        self.lineEdit10 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit10.setMinimumSize(QtCore.QSize(128, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.lineEdit10.setFont(font)
        self.lineEdit10.setStyleSheet("border:1px solid grey;\n"
"border-radius:5px;")
        self.lineEdit10.setObjectName("lineEdit10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit10)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(710, 180, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:transparent")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(710, 250, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color:transparent")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(710, 320, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color:transparent")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(710, 110, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color:transparent")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(370, 320, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color:transparent")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(370, 110, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color:transparent")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(370, 250, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color:transparent")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(370, 180, 56, 16))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color:transparent")
        self.label_17.setObjectName("label_17")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 100, 461, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color :rgb(225, 225, 225);\n"
"border:1px;\n"
"border-radius:5px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(290, 310, 461, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color :rgb(225, 225, 225);\n"
"border:1px;\n"
"border-radius:5px;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 170, 461, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color :rgb(225, 225, 225);\n"
"border:1px;\n"
"border-radius:5px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(290, 240, 461, 61))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color :rgb(225, 225, 225);\n"
"border:1px;\n"
"border-radius:5px;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalScrollBar_5 = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_5.setGeometry(QtCore.QRect(370, 130, 361, 21))
        font = QtGui.QFont()
        font.setFamily("나눔바른고딕")
        self.horizontalScrollBar_5.setFont(font)
        self.horizontalScrollBar_5.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.horizontalScrollBar_5.setMaximum(255)
        self.horizontalScrollBar_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_5.setObjectName("horizontalScrollBar_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(195, 10, 50, 50))
        self.graphicsView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graphicsView.setStyleSheet("background-image:url(:/img/led.png);\n"
"background-color:transparent;\n"
"border:transparent")
        self.graphicsView.setObjectName("graphicsView")
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label_6.raise_()
        self.line.raise_()
        self.horizontalScrollBar_2.raise_()
        self.horizontalScrollBar_3.raise_()
        self.horizontalScrollBar_4.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.SEND.raise_()
        self.EXIT.raise_()
        self.B.raise_()
        self.R.raise_()
        self.G.raise_()
        self.W.raise_()
        self.layoutWidget.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.horizontalScrollBar_5.raise_()
        self.graphicsView.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.horizontalScrollBar_3.valueChanged['int'].connect(self.R.setNum)
        self.horizontalScrollBar_4.valueChanged['int'].connect(self.G.setNum)
        self.horizontalScrollBar_2.valueChanged['int'].connect(self.B.setNum)
        self.horizontalScrollBar_5.valueChanged['int'].connect(self.W.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "                                        LED Dimming Control Program"))
        self.label_2.setText(_translate("MainWindow", "White"))
        self.label_3.setText(_translate("MainWindow", "Red"))
        self.label_4.setText(_translate("MainWindow", "Green"))
        self.label_5.setText(_translate("MainWindow", "Blue"))
        self.SEND.setText(_translate("MainWindow", "SEND"))
        self.EXIT.setText(_translate("MainWindow", "EXIT"))
        self.B.setText(_translate("MainWindow", "0"))
        self.R.setText(_translate("MainWindow", "0"))
        self.G.setText(_translate("MainWindow", "0"))
        self.W.setText(_translate("MainWindow", "0"))
        self.pushButton1.setText(_translate("MainWindow", "1"))
        self.pushButton2.setText(_translate("MainWindow", "2"))
        self.pushButton3.setText(_translate("MainWindow", "3"))
        self.pushButton4.setText(_translate("MainWindow", "4"))
        self.pushButton5.setText(_translate("MainWindow", "5"))
        self.pushButton6.setText(_translate("MainWindow", "6"))
        self.pushButton7.setText(_translate("MainWindow", "7"))
        self.pushButton8.setText(_translate("MainWindow", "8"))
        self.pushButton9.setText(_translate("MainWindow", "9"))
        self.pushButton10.setText(_translate("MainWindow", "10"))
        self.label_10.setText(_translate("MainWindow", "255"))
        self.label_11.setText(_translate("MainWindow", "255"))
        self.label_12.setText(_translate("MainWindow", "255"))
        self.label_13.setText(_translate("MainWindow", "255"))
        self.label_14.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "0"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

